### ISSUE TITLE
NPCs revealing themselves to the PCs 

### ISSUE THREAD

**Issue by LionheadGaming** [sfuqua/fvtt-token-visibility#6]
I'm having an issue whereby selecting my monsters and seeing what they can see, that for some reason updates and provides that information to my players. I can circumvent this by ignoring Token Vision but then I can't tell what my monsters should actually be able to see.

PLAYER INITIAL VIEW
![image](https://user-images.githubusercontent.com/76756218/108612479-20b6ea80-73b7-11eb-8e12-29cf6984c9cb.png)

DM INITIAL VIEW
![image](https://user-images.githubusercontent.com/76756218/108612487-3af0c880-73b7-11eb-9967-242f95b2b3dc.png)

Now I will select a single troll deep within this alcove as the DM. Token Vision set to NOT ignore.

DM VIEW POST TROLL SELECTION

![image](https://user-images.githubusercontent.com/76756218/108612511-6d9ac100-73b7-11eb-8ac5-66d108e5c2ae.png)

Cool, I can tell that the PC is in the road because of the vision of the other trolls closer to her. The problem is the following:

PLAYER VIEW POST DM TROLL SELECTION

![image](https://user-images.githubusercontent.com/76756218/108612534-a175e680-73b7-11eb-8966-e69d030b34e1.png)

Before taking these screenshots I reset Doors and Fog and live during my streamed game last Sunday I encountered this issue and had to disable and restart the server to not spoil the encounter. I don't know what's causing this.

**Comment by sfuqua** [comment]
Thanks for the screenshots and clear reports, I'll try to take a look at this.

I've been having a lot of trouble with edge cases in this module and I'm trying to figure out if I need to deprecate it to avoid unfortunate scenarios like you nearly spoiling your game. I'm fighting Foundry's layers at a pretty fundamental level and weird things happen :(

**Comment by sfuqua** [comment]
I think I have a workaround for this and will publish a fix after some more testing.

**Comment by sfuqua** [comment]
@LionheadGaming I just published 0.2.2 to mitigate this issue. Sorry for the trouble you ran into with your stream, please let me know if you encounter any other major problems. I will try to keep sorting through some of the smaller quirks in my spare time.

**Comment by LionheadGaming** [comment]
Thanks so much for speedy response and quick efforts. I'm sorry if I made it seem like the end of the world, it's all good. I hope maybe with the changes in 0.8.0 or something it'll even out for you this is a really great module to have honestly and something I'd personally wish was built into the core lighting and vision along side Perfect Vision.
